# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-mskW9L4Am19zAG1UGnJjYjrBqOcbM4v
"""

!pip install nfl_data_py
import nfl_data_py as nfl
data = nfl.import_seasonal_data([2022])
data = nfl.clean_nfl_data(data)
#list(data)
data.head()
data.shape